### ISSUE TITLE
[tmux] Native support XDG specs of oh-my-tmux

### ISSUE THREAD

**Issue by latipun7** [latipun7/dotfiles#11]
## Assurance

- [X] I have read and understand the contribution guide, and
- [X] I'm sure there's no relevant issue in this repository

## Description

Change oh-my-tmux configuration path to XDG base dir natively.

## Task List

- [x] https://github.com/gpakosz/.tmux/issues/439
- [x] Remove https://github.com/latipun7/dotfiles/blob/8ef5fa7d0682943e2b3680fab5f0da5ba533de63/home/.chezmoiscripts/run_after_50-tmux-conf-path.tmpl
